# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/tempMNIST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/tempMNIST

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/tempMNIST/CMakeFiles /mnt/d/tempMNIST/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/tempMNIST/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TempMNIST

# Build rule for target.
TempMNIST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TempMNIST
.PHONY : TempMNIST

# fast build rule for target.
TempMNIST/fast:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/build
.PHONY : TempMNIST/fast

ImageHeader.o: ImageHeader.cpp.o

.PHONY : ImageHeader.o

# target to build an object file
ImageHeader.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/ImageHeader.cpp.o
.PHONY : ImageHeader.cpp.o

ImageHeader.i: ImageHeader.cpp.i

.PHONY : ImageHeader.i

# target to preprocess a source file
ImageHeader.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/ImageHeader.cpp.i
.PHONY : ImageHeader.cpp.i

ImageHeader.s: ImageHeader.cpp.s

.PHONY : ImageHeader.s

# target to generate assembly for a file
ImageHeader.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/ImageHeader.cpp.s
.PHONY : ImageHeader.cpp.s

LabelHeader.o: LabelHeader.cpp.o

.PHONY : LabelHeader.o

# target to build an object file
LabelHeader.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/LabelHeader.cpp.o
.PHONY : LabelHeader.cpp.o

LabelHeader.i: LabelHeader.cpp.i

.PHONY : LabelHeader.i

# target to preprocess a source file
LabelHeader.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/LabelHeader.cpp.i
.PHONY : LabelHeader.cpp.i

LabelHeader.s: LabelHeader.cpp.s

.PHONY : LabelHeader.s

# target to generate assembly for a file
LabelHeader.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/LabelHeader.cpp.s
.PHONY : LabelHeader.cpp.s

Layer.o: Layer.cpp.o

.PHONY : Layer.o

# target to build an object file
Layer.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Layer.cpp.o
.PHONY : Layer.cpp.o

Layer.i: Layer.cpp.i

.PHONY : Layer.i

# target to preprocess a source file
Layer.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Layer.cpp.i
.PHONY : Layer.cpp.i

Layer.s: Layer.cpp.s

.PHONY : Layer.s

# target to generate assembly for a file
Layer.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Layer.cpp.s
.PHONY : Layer.cpp.s

Neuron.o: Neuron.cpp.o

.PHONY : Neuron.o

# target to build an object file
Neuron.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Neuron.cpp.o
.PHONY : Neuron.cpp.o

Neuron.i: Neuron.cpp.i

.PHONY : Neuron.i

# target to preprocess a source file
Neuron.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Neuron.cpp.i
.PHONY : Neuron.cpp.i

Neuron.s: Neuron.cpp.s

.PHONY : Neuron.s

# target to generate assembly for a file
Neuron.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Neuron.cpp.s
.PHONY : Neuron.cpp.s

Perceptron.o: Perceptron.cpp.o

.PHONY : Perceptron.o

# target to build an object file
Perceptron.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Perceptron.cpp.o
.PHONY : Perceptron.cpp.o

Perceptron.i: Perceptron.cpp.i

.PHONY : Perceptron.i

# target to preprocess a source file
Perceptron.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Perceptron.cpp.i
.PHONY : Perceptron.cpp.i

Perceptron.s: Perceptron.cpp.s

.PHONY : Perceptron.s

# target to generate assembly for a file
Perceptron.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Perceptron.cpp.s
.PHONY : Perceptron.cpp.s

Result.o: Result.cpp.o

.PHONY : Result.o

# target to build an object file
Result.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Result.cpp.o
.PHONY : Result.cpp.o

Result.i: Result.cpp.i

.PHONY : Result.i

# target to preprocess a source file
Result.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Result.cpp.i
.PHONY : Result.cpp.i

Result.s: Result.cpp.s

.PHONY : Result.s

# target to generate assembly for a file
Result.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/Result.cpp.s
.PHONY : Result.cpp.s

UtilityFunctions.o: UtilityFunctions.cpp.o

.PHONY : UtilityFunctions.o

# target to build an object file
UtilityFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/UtilityFunctions.cpp.o
.PHONY : UtilityFunctions.cpp.o

UtilityFunctions.i: UtilityFunctions.cpp.i

.PHONY : UtilityFunctions.i

# target to preprocess a source file
UtilityFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/UtilityFunctions.cpp.i
.PHONY : UtilityFunctions.cpp.i

UtilityFunctions.s: UtilityFunctions.cpp.s

.PHONY : UtilityFunctions.s

# target to generate assembly for a file
UtilityFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/UtilityFunctions.cpp.s
.PHONY : UtilityFunctions.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TempMNIST.dir/build.make CMakeFiles/TempMNIST.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... TempMNIST"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... ImageHeader.o"
	@echo "... ImageHeader.i"
	@echo "... ImageHeader.s"
	@echo "... LabelHeader.o"
	@echo "... LabelHeader.i"
	@echo "... LabelHeader.s"
	@echo "... Layer.o"
	@echo "... Layer.i"
	@echo "... Layer.s"
	@echo "... Neuron.o"
	@echo "... Neuron.i"
	@echo "... Neuron.s"
	@echo "... Perceptron.o"
	@echo "... Perceptron.i"
	@echo "... Perceptron.s"
	@echo "... Result.o"
	@echo "... Result.i"
	@echo "... Result.s"
	@echo "... UtilityFunctions.o"
	@echo "... UtilityFunctions.i"
	@echo "... UtilityFunctions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

